services:
  db:
    container_name: database-ingestion
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dataflow
    ports:
      - "5432:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data

  minio:
    container_name: datalake
    image: minio/minio
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - miniodata:/data

  ingestion_api:
    container_name: ingestion_api
    build:
      context: ./ingestion/api
      dockerfile: Dockerfile.api
    depends_on:
      - minio

volumes:
  pgdata:
  miniodata: