services:
  db:
    container_name: database-ingestion
    image: postgres
    networks:
      - airflow_net
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dataflow
    ports:
      - "5432:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data

  minio:
    container_name: datalake
    image: minio/minio
    networks:
      - airflow_net
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - miniodata:/data

  airflow:
    container_name: airflow
    image: apache/airflow:2.9.1
    user: "0:0"
    networks:
      - airflow_net
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: sqlite:////opt/airflow/airflow.db
    volumes:
      - ./dags:/opt/airflow/dags
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
    command: >
      bash -c "
        airflow db migrate &&
        airflow users create --username admin --firstname admin --lastname admin --role Admin --email admin@example.com --password admin &&
        airflow webserver
      "

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    networks:
      - airflow_net
    environment:
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      ALLOW_PLAINTEXT_LISTENER: yes
    ports:
      - "9092:9092"

  api_producer:
    container_name: api_producer
    build:
      context: ./ingestion/producers/api
      dockerfile: Dockerfile.api_producer
    depends_on:
      - kafka
    networks:
      - airflow_net

  api_consumer:
    container_name: api_consumer
    build:
      context: ./ingestion/consumers/api
      dockerfile: Dockerfile.api_consumer
    depends_on:
      - minio
      - kafka
    networks:
      - airflow_net

  csv_producer:
    container_name: csv_producer
    build:
      context: ./ingestion/producers/csv
      dockerfile: Dockerfile.csv_producer
    depends_on:
      - kafka
    networks:
      - airflow_net

  csv_consumer:
    container_name: csv_consumer
    build:
      context: ./ingestion/consumers/csv
      dockerfile: Dockerfile.csv_consumer
    depends_on:
      - minio
      - kafka
    networks:
      - airflow_net

  database_producer:
    container_name: database_producer
    build:
      context: ./ingestion/producers/database
      dockerfile: Dockerfile.database_producer
    depends_on:
      - kafka
      - db
    networks:
      - airflow_net

  database_consumer:
    container_name: database_consumer
    build:
      context: ./ingestion/consumers/database
      dockerfile: Dockerfile.database_consumer
    depends_on:
      - minio
      - kafka
    networks:
      - airflow_net

networks:
  airflow_net:

volumes:
  pgdata:
  miniodata:
  dags: