version: '3.8'

services:
  db:
    container_name: database-ingestion
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dataflow
    ports:
      - "5432:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data

  minio:
    container_name: datalake
    image: minio/minio
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - miniodata:/data

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    environment:
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      ALLOW_PLAINTEXT_LISTENER: "yes"
    ports:
      - "9092:9092"
    healthcheck:
      test: ["CMD", "kafka-topics.sh", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 10s
      timeout: 5s
      retries: 10

  api_producer:
    container_name: api_producer
    build:
      context: ./ingestion/producers/api
      dockerfile: Dockerfile.api_producer
    depends_on:
      kafka:
        condition: service_healthy
    restart: on-failure

  api_consumer:
    container_name: api_consumer
    build:
      context: ./ingestion/consumers/api
      dockerfile: Dockerfile.api_consumer
    depends_on:
      minio:
        condition: service_started
      kafka:
        condition: service_healthy
    restart: on-failure

  csv_producer:
    container_name: csv_producer
    build:
      context: ./ingestion/producers/csv
      dockerfile: Dockerfile.csv_producer
    depends_on:
      kafka:
        condition: service_healthy
    restart: on-failure

  csv_consumer:
    container_name: csv_consumer
    build:
      context: ./ingestion/consumers/csv
      dockerfile: Dockerfile.csv_consumer
    depends_on:
      minio:
        condition: service_started
      kafka:
        condition: service_healthy
    restart: on-failure

  database_producer:
    container_name: database_producer
    build:
      context: ./ingestion/producers/database
      dockerfile: Dockerfile.database_producer
    depends_on:
      db:
        condition: service_started
      kafka:
        condition: service_healthy
    volumes:
      - ./ingestion/producers/database:/app
    restart: on-failure

  database_consumer:
    container_name: database_consumer
    build:
      context: ./ingestion/consumers/database
      dockerfile: Dockerfile.database_consumer
    depends_on:
      minio:
        condition: service_started
      kafka:
        condition: service_healthy
    volumes:
      - ./ingestion/consumers/database:/app
    restart: on-failure

  transform_csv:
    container_name: transform_csv
    build:
      context: ./transformers/csv
      dockerfile: Dockerfile.transform_csv
    depends_on:
      db:
        condition: service_started
      minio:
        condition: service_started
      kafka:
        condition: service_healthy
    volumes:
      - ./transformers/csv:/app
    restart: on-failure

  transform_database:
    container_name: transform_database
    build:
      context: ./transformers/database
      dockerfile: Dockerfile.transform_database
    depends_on:
      db:
        condition: service_started
      minio:
        condition: service_started
      kafka:
        condition: service_healthy
    volumes:
      - ./transformers/database:/app
    restart: on-failure

  transform_parquet:
    container_name: transform_parquet
    build:
      context: ./transformers/parquet
      dockerfile: Dockerfile.transform_parquet
    depends_on:
      db:
        condition: service_started
      minio:
        condition: service_started
      kafka:
        condition: service_healthy
    volumes:
      - ./transformers/parquet:/app
    restart: on-failure

volumes:
  pgdata:
  miniodata: